# Generated by Django 4.0.4 on 2022-05-24 06:53

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=customers.models.get_default_profile_image, max_length=255, null=True, upload_to=customers.models.get_profile_image_filepath),
        ),
    ]
