# Generated by Django 4.0.4 on 2022-05-24 07:01

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=customers.models.get_profile_image_filepath),
        ),
    ]
