# Generated by Django 4.0.4 on 2022-05-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
