# Generated by Django 3.2.7 on 2022-05-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20220529_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_text',
            field=models.CharField(max_length=1200),
        ),
    ]
