# Generated by Django 3.2.7 on 2022-05-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_address_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='ایران', max_length=40),
        ),
    ]
