# Generated by Django 3.2.7 on 2022-06-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name_plural': 'DiscountCodes'},
        ),
    ]
