# Generated by Django 3.2.7 on 2022-06-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_discountcode_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
