# Generated by Django 3.2.7 on 2022-06-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
