# Generated by Django 3.2.7 on 2022-05-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='order_status',
        ),
    ]
