# Generated by Django 3.2.13 on 2022-05-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
