# Generated by Django 3.2.13 on 2022-05-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
    ]
