# Generated by Django 3.2.13 on 2022-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220527_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
