# Generated by Django 3.2.7 on 2022-06-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
